[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "cd shared && npm install",
  "cd websocket-server && npm install"
]

[phases.build]
cmds = ["cd websocket-server && npm run build"]

[start]
cmd = "cd websocket-server && npm start"
