[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "npm install --workspaces=false",
  "npm install --workspace=shared",
  "npm install --workspace=websocket-server"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
